package com.learn.springboot.model;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cat
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Cat implements Serializable{

    private Integer id;

    @Max(value=100)
    @Min(value=0)
    private Integer catAge;

    @NotNull(message = "catName不能为空")
    private String catName;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCatAge() {
        return catAge;
    }

    public void setCatAge(Integer catAge) {
        this.catAge = catAge;
    }

    public String getCatName() {
        return catName;
    }

    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    public Cat(Integer id, Integer catAge, String catName) {
        this.id = id;
        this.catAge = catAge;
        this.catName = catName;
    }

    public Cat(Integer catAge, String catName) {
        this.catAge = catAge;
        this.catName = catName;
    }

    public Cat() {
    }
}